# Generated by Django 4.0.3 on 2022-11-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='file_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='files',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='files',
            name='tag',
        ),
        migrations.AddField(
            model_name='files',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
