# Generated by Django 4.0.3 on 2022-11-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorap', '0002_rename_file_name_files_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='title',
        ),
    ]
