# Generated by Django 4.0.3 on 2022-11-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorap', '0004_fileupload_delete_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='content',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='title',
        ),
    ]
