# Generated by Django 4.0.3 on 2022-11-30 08:13

from django.db import migrations, models
import sorap.models


class Migration(migrations.Migration):

    dependencies = [
        ('sorap', '0007_alter_fileupload_imgfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=sorap.models.user_directory_path),
        ),
    ]
