# Generated by Django 4.0.3 on 2022-11-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorap', '0008_alter_fileupload_imgfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file_name',
            field=models.TextField(null=True),
        ),
    ]
